from flask import Flask, render_template, Response
import datetime
from icalendar import Calendar, Event, vText, vRecur, vDDDTypes
import sqlite3

SCHEMA = """
    CREATE TABLE IF NOT EXISTS contacts
        (id integer primary key autoincrement, name text, birthday int, birthmonth int, birthyear int)
"""

conn = sqlite3.connect("data/contacts.db")
cursor = conn.cursor()
cursor.execute(SCHEMA)
conn.commit()

app = Flask(__name__)

@app.route('/')
def index():
    return render_template('index.html')

@app.route('/contacts.ics')
def contacts_ics():
    cal = Calendar()
    cal.add('prodid', vText('-//choochootrain//Auto-generated//EN'))
    cal.add('version', vText('2.0'))
    cal.add('calscale', vText('gregorian'))
    cal.add('method', vText('publish'))

    cal.add('x-wr-calname', vText('Birthdays'))
    cal.add('x-wr-timezone', vText('America/Los_Angeles'))
    cal.add('x-wr-caldesc', vText('Autogenerated calendar of birthday events'))

    conn = sqlite3.connect("data/contacts.db")
    cursor = conn.cursor()
    cursor.execute("SELECT * FROM contacts order by birthyear, birthmonth, birthday")

    for id, name, day, month, year in cursor.fetchall():
        event = Event()
        event.add('summary', "%s's birthday" % name)

        start = datetime.datetime(day=day, month=month, year=year if year is not None else 2014)
        event.add('dtstart', vDDDTypes(start))
        event.add('dtend', vDDDTypes(start + datetime.timedelta(days=1)))
        event.add('rrule', vRecur(freq='yearly'))
        cal.add_component(event)

    return Response(cal.to_ical(), mimetype="text/calendar")

app.run(debug=True)
